name: Platform CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        env:
          PYTHONPATH: .
        run: pytest

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::357919579947:role/preview-github-actions-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dev-platform
          IMAGE_TAG: ${{ github.sha }}
          PR_TAG: pr-${{ github.event.pull_request.number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$PR_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$PR_TAG

      # --- TERRAFORM DEPLOYMENT ---

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Deploy Ephemeral Environment via Terraform
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd terraform/modules/preview-env
          terraform init -backend-config="key=env/pr-${PR_NUM}.tfstate"
          terraform apply -auto-approve \
            -var="pr_number=${PR_NUM}" \
            -var="image_tag=${IMAGE_TAG}"

